apiVersion: apps/v1
kind: Deployment
metadata:
  name: filme-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filme-service
  template:
    metadata:
      labels:
        app: filme-service
    spec:
      containers:
        - name: filme-service
          image: mateusol22/crud-filme-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
