apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\mateu\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Thu, 19 Sep 2024 23:11:32 -03
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://127.0.0.1:46074
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 19 Sep 2024 23:11:32 -03
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\mateu\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\mateu\.minikube\profiles\minikube\client.key
